fid = fopen('configurations/camera.json','r','n','UTF-8');
config = fscanf(fid, '%s');
message = jsondecode(config);
msg = struct(...
'type', "REPLAY_ConfigureSensorsCommand_ID",...
'message', [message(1,:);],...
'reference', randi(1000));

%'message', jsonencode([message(2,:);message(3,:)]),...
