import os
from uut import BASE_FIXTURE_PATH


ELASTIC_IP = 'OVERRIDE'
ELASTIC_PORT = 9200
ELASTIC_URL  = 'http://{0}:{1}'.format(ELASTIC_IP, ELASTIC_PORT)
ELASTIC_USER = 'OVERRIDE'
ELASTIC_PASS = 'OVERRIDE'

KIBANA_IP = 'OVERRIDE'
KIBANA_PORT = 5601
KIBANA_URL = 'http://{0}:{1}'.format(KIBANA_IP, KIBANA_PORT)
KIBANA_USER = 'OVERRIDE'
KIBANA_PASS = 'OVERRIDE'

KIBANA_BACKUP_LOCATION = os.path.join(BASE_FIXTURE_PATH, 'elk', 'saved_objects_backup.json')
KIBANA_DEFAULT_INDEX_NAME = 'report'